mainConfig:
  appName: "offer-pilot"
  host: "0.0.0.0"
  port: 9090

emailConfig:
  authcode: "vqqocpwnzmzlbdhb"
  email: "1019426464@qq.com"

redisConfig:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  captchaPrefix: "captcha:%s"

mysqlConfig:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "lwr2005718"
  databaseName: "offer-pilot"
  charset: "utf8mb4"

jwtConfig:
  expire_duration: 8760
  issuer: "huanheart"
  subject: "OfferPilot"
  key: "OfferPilot"

rabbitmqConfig:
  host: "192.168.175.161"
  port: 5672
  username: "admi"
  password: "123456"
  vhost: "/"
